baseURL = 'https://zhengyu.de/'
languageCode = 'zh-cn'
title = 'ZhengYu'
theme = 'yinyang'
canonifyURLs = false
enableRobotsTXT = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
noClasses = true
style = "tango"
tabWidth = 2


[params]
  # description abou this website
  headTitle = "ZhengYu"
  description = "内观则自知，自治则自明。自明则不争讼，安之若素，如如不动"
  staticPrefix = "https://cdn.jsdelivr.net/gh/ooapex/blog"
  cusdis = true
  cusdisAppId = "03d2d89e-f0de-42be-95de-b6daa304646e"
  favicon = "/favicon.png"

[[params.author]]
homepage = "https://zhengyu.de/"
name = "zhengyu"