baseURL = 'https://ooapex.com/'
languageCode = 'zh-cn'
title = 'OOAPEX'
theme = 'hugo-ivy'
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[menu]
  [[menu.main]]
  name="博客"
  url="/posts/"
  weight="1"
  [[menu.main]]
  name="阅读"
  url="/books/"
  weight="2"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="3"

[params]
  # description abou this website
  description = "内观则自知，自治则自明。自明则不争讼，安之若素，如如不动"
  footer = "&copy; [Elizen](https://ooapex.me) | since 2024"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1