baseURL = 'https://ooapex.com/'
languageCode = 'zh-cn'
title = 'OOAPEX'
theme = 'yinyang'
canonifyURLs = false
enableRobotsTXT = true

[params]
  # description abou this website
  headTitle = "OOAPEX"
  description = "内观则自知，自治则自明。自明则不争讼，安之若素，如如不动"

[[params.author]]
homepage = "https://ooapex.com/"
name = "Ishland"